config/routes.rb
Rails.application.routes.draw do
  resources :montagem_pecas
  resources :montagems
  resources :pecas
  resources :accounts
  resources :fornecedors
  root 'home#index'
  resources :livros
  resources :autors
  get '/relatorios/relatorio_autor', to: 'relatorios#relatorio_autor'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/montagem.rb
class Montagem < ApplicationRecord
    belongs_to :livro
    has_and_belongs_to_many :pecas, join_table: 'montagem_pecas'

    def total_valor_pecas
        pecas.sum(:valor)
    end
end

app/controllers/montagems_controller.rb
class MontagemsController < ApplicationController
  before_action :set_montagem, only: %i[ show edit update destroy ]

  # GET /montagems or /montagems.json
  def index
    @montagems = Montagem.all
  end

  # GET /montagems/1 or /montagems/1.json
  def show
  end

  # GET /montagems/new
  def new
    @montagem = Montagem.new
  end

  # GET /montagems/1/edit
  def edit
  end

  # POST /montagems or /montagems.json
  def create
    @montagem = Montagem.new(montagem_params)

    respond_to do |format|
      if @montagem.save
        format.html { redirect_to montagem_url(@montagem), notice: "Montagem was successfully created." }
        format.json { render :show, status: :created, location: @montagem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @montagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /montagems/1 or /montagems/1.json
  def update
    respond_to do |format|
      if @montagem.update(montagem_params)
        format.html { redirect_to montagem_url(@montagem), notice: "Montagem was successfully updated." }
        format.json { render :show, status: :ok, location: @montagem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @montagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /montagems/1 or /montagems/1.json
  def destroy
    @montagem.destroy

    respond_to do |format|
      format.html { redirect_to montagems_url, notice: "Montagem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_montagem
      @montagem = Montagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def montagem_params
      params.require(:montagem).permit(:nome, :livro_id, peca_ids: [])
    end
end

app/helpers/montagems_helper.rb
module MontagemsHelper
end

app/views/montagems/_form.html.erb
<%= form_with(model: montagem) do |form| %>
  <% if montagem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(montagem.errors.count, "error") %> prohibited this montagem from being saved:</h2>

      <ul>
        <% montagem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :livro_id, style: "display: block" %>
    <%= form.collection_select :livro_id, Livro.all, :id, :titulo, {}, { class: 'autor-select' } %>
  </div>

  <div class="peca-fields">


    <% montagem.peca_ids.each do |peca_id| %>
      <div class="peca-field">
        <%= form.collection_select :peca_ids, Peca.all, :id, :nome, { selected: peca_id }, { class: 'peca-select' } %>
        <%= link_to "Remover", "#", class: "remove-peca-button" %>
      </div>
    <% end %>

    <div class="add-peca">
      <%= link_to "Adicionar peça", "#", class: "add-peca-button" %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const addPecaButton = document.querySelector(".add-peca-button");
        const pecaFieldsContainer = document.querySelector(".peca-fields");

        let pecaCounter = 1;

        addPecaButton.addEventListener("click", function(event) {
            event.preventDefault();

            const newPecaField = document.createElement("div");
            newPecaField.innerHTML = `
        <div class="peca-field">
          <label for="montagem_peca_ids_${pecaCounter}"/label>
          <select class="peca-select" name="montagem[peca_ids][]" ...>
            <%= options_from_collection_for_select(Peca.all, :id, :nome) %>
          </select>
          <a href="#" class="remove-peca-button">Remover</a>
        </div>
      `;

            pecaFieldsContainer.appendChild(newPecaField);
            pecaCounter++;
        });

        pecaFieldsContainer.addEventListener("click", function(event) {
            if (event.target.classList.contains("remove-peca-button")) {
                event.preventDefault();
                event.target.closest(".peca-field").remove();
            }
        });
    });
</script>

app/views/montagems/_montagem.html.erb
<div id="<%= dom_id montagem %>">
  <p>
    <strong>Nome:</strong>
    <%= montagem.nome %>
  </p>

  <p>
    <strong>Livro:</strong>
    <%= montagem.livro.titulo%>
  </p>

  <p>
    <strong>Peças:</strong><br>
    <% montagem.pecas.each do |peca| %>
      <%= "Número: #{peca.numero} - #{peca.nome} - Valor: R$#{peca.valor}" %><br>
    <% end %>
  </p>



  <p>
    <strong>Valor total:</strong>
    <%= number_to_currency(montagem.total_valor_pecas, unit: "R$", separator: ",") %>
  </p>


</div>

app/views/montagems/edit.html.erb
<h1>Editing montagem</h1>

<%= render "form", montagem: @montagem %>

<br>

<div>
  <%= link_to "Show this montagem", @montagem %> |
  <%= link_to "Back to montagems", montagems_path %>
</div>

app/views/montagems/index.html.erb
<h1>Montagens</h1>

<div id="montagems">
  <% @montagems.each do |montagem| %>
    <%= render montagem %>
    <p>
      <%= link_to "Show this montagem", montagem %>
    </p>
  <% end %>
</div>

<%= link_to "New montagens", new_montagem_path %>

app/views/montagems/new.html.erb
<h1>New montagem</h1>

<%= render "form", montagem: @montagem %>

<br>

<div>
  <%= link_to "Back to montagens", montagems_path %>
</div>

app/views/montagems/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @montagem %>

<div>
  <%= link_to "Edit this montagem", edit_montagem_path(@montagem) %> |
  <%= link_to "Back to montagems", montagems_path %>

  <%= button_to "Destroy this montagem", @montagem, method: :delete %>
</div>