config/routes.rb
Rails.application.routes.draw do
  resources :montagem_pecas
  resources :montagems
  resources :pecas
  resources :accounts
  resources :fornecedors
  root 'home#index'
  resources :livros
  resources :autors
  get '/relatorios/relatorio_autor', to: 'relatorios#relatorio_autor'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/peca.rb
class Peca < ApplicationRecord
    belongs_to :fornecedor
    has_and_belongs_to_many :montagems, join_table: 'montagem_pecas'

    scope :by_fornecedor_nome, ->(query) { joins(:fornecedor).where("fornecedors.nome LIKE ?", "%#{query}%") }


end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  before_action :set_peca, only: %i[ show edit update destroy ]

  # GET /pecas or /pecas.json
  def index
    @pecas = Peca.by_fornecedor_nome(params[:search]) if (params[:search]) and (params[:search_type] == 'fornecedor_nome')
    @pecas = Peca.all unless params[:search]
  end

  # GET /pecas/1 or /pecas/1.json
  def show
  end

  # GET /pecas/new
  def new
    @peca = Peca.new
  end

  # GET /pecas/1/edit
  def edit
  end

  # POST /pecas or /pecas.json
  def create
    @peca = Peca.new(peca_params)

    respond_to do |format|
      if @peca.save
        format.html { redirect_to peca_url(@peca), notice: "Peca was successfully created." }
        format.json { render :show, status: :created, location: @peca }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pecas/1 or /pecas/1.json
  def update
    respond_to do |format|
      if @peca.update(peca_params)
        format.html { redirect_to peca_url(@peca), notice: "Peca was successfully updated." }
        format.json { render :show, status: :ok, location: @peca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pecas/1 or /pecas/1.json
  def destroy
    @peca.destroy

    respond_to do |format|
      format.html { redirect_to pecas_url, notice: "Peca was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peca
      @peca = Peca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def peca_params
      params.require(:peca).permit(:numero, :nome, :valor, :fornecedor_id)
    end
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/views/pecas/_form.html.erb
<%= form_with(model: peca) do |form| %>
  <% if peca.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(peca.errors.count, "error") %> prohibited this peca from being saved:</h2>

      <ul>
        <% peca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.label :fornecedor_id, style: "display: block" %>
  <%= form.collection_select :fornecedor_id, Fornecedor.all, :id, :nome, {}, { class: 'autor-select' } %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.number_field :numero %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pecas/_peca.html.erb
<div id="<%= dom_id peca %>">
  <p>
    <strong>Numero:</strong>
    <%= peca.numero %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= peca.nome %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= peca.valor %>
  </p>

  <p>
    <strong>Fornecedor:</strong>
    <%= peca.fornecedor.nome %>
  </p>

</div>

app/views/pecas/edit.html.erb
<h1>Editing peca</h1>

<%= render "form", peca: @peca %>

<br>

<div>
  <%= link_to "Show this peca", @peca %> |
  <%= link_to "Back to pecas", pecas_path %>
</div>

app/views/pecas/index.html.erb
<%= form_tag(pecas_path, method: :get) do %>
  <p> Filtrar por:
    <%= radio_button_tag 'search_type', 'fornecedor_nome', true %>
    Fornecedor
    <%= text_field_tag 'search', nil, placeholder: 'Digite o fornecedor...' %>
    <%= submit_tag "Filtrar" %>
  </p>
<% end %>

<h1>Pecas</h1>

<div id="pecas">
  <% @pecas.each do |peca| %>
    <%= render peca %>
    <p>
      <%= link_to "Show this peca", peca %>
    </p>
  <% end %>
</div>

<%= link_to "New peca", new_peca_path %>

app/views/pecas/new.html.erb
<h1>New peca</h1>

<%= render "form", peca: @peca %>

<br>

<div>
  <%= link_to "Back to pecas", pecas_path %>
</div>

app/views/pecas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @peca %>

<div>
  <%= link_to "Edit this peca", edit_peca_path(@peca) %> |
  <%= link_to "Back to pecas", pecas_path %>

  <%= button_to "Destroy this peca", @peca, method: :delete %>
</div>