config/routes.rb
Rails.application.routes.draw do
  resources :montagem_pecas
  resources :montagems
  resources :pecas
  resources :accounts
  resources :fornecedors
  root 'home#index'
  resources :livros
  resources :autors
  get '/relatorios/relatorio_autor', to: 'relatorios#relatorio_autor'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to :autor
  has_many :montagems

  def nome
    autor.nome if autor
  end


  validates :titulo, presence: true
  validates :titulo, length: { minimum:1, maximum:100 }
  validates :isbn, presence: true
  # validates :isbn, uniqueness: true
  # validate :isbn_is_valid?

  scope :search, ->(query) { where("titulo like ?", "%#{query}%") }
  scope :by_autor_nome, ->(query) { joins(:autor).where("LOWER(autors.nome) LIKE ?", "%#{query.downcase}%") }


  private
  def isbn_is_valid?
    errors.add(:isbn, "ISBN inválido! Por favor, verifique os dados.") unless ISBN.valid?(self.isbn)
  end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.search(params[:search]) if (params[:search]) and (params[:search_type] == 'livro_titulo')
    @livros = Livro.by_autor_nome(params[:search]) if (params[:search]) and (params[:search_type] == 'autor_nome')
    @livros = Livro.all unless params[:search]
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor_id, :publicado, :isbn)
    end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.label :autor_id, style: "display: block" %>
  <%= form.collection_select :autor_id, Autor.all, :id, :nome, {}, { class: 'autor-select' } %>
  </div>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :publicado, style: "display: block" %>
    <%= form.text_field :publicado %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <p>
    <strong>Titulo:</strong>
    <%= livro.titulo %>
  </p>

  <p>
    <strong>ID:</strong>
    <%= livro.autor_id %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= livro.nome %>
  </p>

  <p>
    <strong>Publicado:</strong>
    <%= livro.publicado %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= livro.isbn %>
  </p>

</div>

app/views/livros/edit.html.erb
<h1>Editing livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Show this livro", @livro %> |
  <%= link_to "Back to livros", livros_path %>
</div>

app/views/livros/index.html.erb
 <%= form_tag(livros_path, method: :get) do %>
   <p> Filtrar por:
     <%= radio_button_tag 'search_type', 'livro_titulo', true %>
     Titulo
     <%= radio_button_tag 'search_type', 'autor_nome' %>
     Autor (nome)
     <%= text_field_tag 'search', nil, placeholder: 'Digite o título ou autor do livro...' %>
     <%= submit_tag "Filtrar" %>
   </p>
 <% end %>

<h1>Livros</h1>

<div id="livros">
  <% @livros.each do |livro| %>
    <%= render livro %>
    <p>
      <%= link_to "Show this livro", livro %>
    </p>
  <% end %>
</div>

<%= link_to "New livro", new_livro_path %>

app/views/livros/new.html.erb
<h1>New livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Back to livros", livros_path %>
</div>

app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livro %>


<div>
  <%= link_to "Edit this livro", edit_livro_path(@livro) %> |
  <%= link_to "Back to livros", livros_path %>

  <%= button_to "Destroy this livro", @livro, method: :delete %>
</div>