config/routes.rb
Rails.application.routes.draw do
  resources :montagem_pecas
  resources :montagems
  resources :pecas
  resources :accounts
  resources :fornecedors
  root 'home#index'
  resources :livros
  resources :autors
  get '/relatorios/relatorio_autor', to: 'relatorios#relatorio_autor'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>Minha Aplicação</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'print', media: 'print' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="sidebar">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "Autores", autors_path %></div>
      <div><%= link_to "Livros", livros_path %></div>
      <div><%= link_to "Fornecedores", fornecedors_path %></div>
      <div><%= link_to "Contas", accounts_path %></div>
      <div><%= link_to "Peças", pecas_path %></div>
      <div><%= link_to "Montagens", montagems_path %></div>
      <div><%= link_to "Relatórios", relatorios_relatorio_autor_path %></div>
    </div>

    <div class="main-content">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!-- app/views/layouts/home.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>Página Inicial Editora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>